[workspace]
resolver = "2"
members = [
  "interface",
  "program",
]

[package]
name = "spl-token-group-interface"
version = "0.2.4"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
path = "interface/src/lib.rs"

[dependencies]
spl-pod = { git = "https://github.com/hamkj7hpo/spl-pod.git", rev = "c1b81ff0773a434bd456dcbf2890a12003d70dca", package = "spl-pod", default-features = false }
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", rev = "079536b934de349771fa8a0e9945bcef01f529cc", package = "solana-program" }
spl-discriminator = "0.4.1"
spl-program-error = "0.4.2"
bytemuck = { version = "1.17.1", features = ["derive"] }
